
  CREATE TABLE "WA_SGCPF_RATE" 
   (	"ORGTYPE" VARCHAR2(20) DEFAULT '~', 
	"CONTRIBUTION_TYPE" VARCHAR2(20) DEFAULT '~', 
	"AGE_LOWER" NUMBER(*,0), 
	"AGE_UPPER" NUMBER(*,0), 
	"OW_CEILLING" NUMBER(28,8), 
	"AW_FIXVALUE" NUMBER(28,8), 
	"TOTALWAGE_LOWER" NUMBER(28,8), 
	"TOTALWAGE_UPPER" NUMBER(28,8), 
	"TOTALCPF_FORMULA" VARCHAR2(101), 
	"EMPLOYEECPF_FORMULA" VARCHAR2(101), 
	"CPFCODE" VARCHAR2(20), 
	"CYEAR" VARCHAR2(4), 
	"EFFECTIVE_DATE" CHAR(19), 
	"EXPIRATION_DATE" CHAR(19), 
	"OWEE_FORMLA" VARCHAR2(101), 
	"OWTOTAL_FORMULA" VARCHAR2(101), 
	"AWEE_FORMULA" VARCHAR2(101), 
	"AWTOTAL_FORMULA" VARCHAR2(101)
   ) 
