/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.hrrp.pdfrep;

import nc.md.model.impl.MDEnum;
import nc.md.model.IEnumValue;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
public class TotalRangeEnum extends MDEnum{
	public TotalRangeEnum(IEnumValue enumvalue){
		super(enumvalue);
	}
	
public static final TotalRangeEnum CURRENTPAGE= MDEnum.valueOf(TotalRangeEnum.class, "-1");
public static final TotalRangeEnum BEFOREPAGE= MDEnum.valueOf(TotalRangeEnum.class, "-2");
public static final TotalRangeEnum TOTALPAGE= MDEnum.valueOf(TotalRangeEnum.class, "-3");
	

} 
