/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wa.item;

import java.io.Serializable;

import nc.md.model.impl.MDEnum;
import nc.md.model.IEnumValue;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
public class SeaLocalEnum extends MDEnum implements Serializable {
	
	private static final long serialVersionUID = 1368349383043247773L;

	public SeaLocalEnum(IEnumValue enumvalue){
		super(enumvalue);
	}
	
	public static final SeaLocalEnum NORMAL_REMUNERATION = MDEnum.valueOf(
			SeaLocalEnum.class, 0);
	public static final SeaLocalEnum ADDITIONAL_REMUNERATION = MDEnum.valueOf(
			SeaLocalEnum.class, 1);
	public static final SeaLocalEnum OPTIONAL_DEDUCTION = MDEnum.valueOf(
			SeaLocalEnum.class, 2);
	public static final SeaLocalEnum OTHERS = MDEnum.valueOf(
			SeaLocalEnum.class, 3);

	@Override
	public Integer value() {
		return (Integer) super.value();
	}
} 
